runtime: java17 # or another supported runtime
service: ${GAE_SERVICE}
entrypoint: java -jar app.jar
env_variables:
    OIDC_ALLOW_ALL: "true"
    OIDC_ADD_ALL: "true"
    OIDC_DOMAIN: "${OIDC_DOMAIN}"
    OIDC_ISSUER: "https://${GAE_SERVICE}-dot-${GCP_PROJECT_ID}.appspot.com"
    OIDC_CLIENT_ID: "${OIDC_CLIENT_ID}"
    OIDC_CLIENT_SECRET: "${OIDC_CLIENT_SECRET}"
    OIDC_REDIRECTS: "https://${FIREBASE_PROJECT_ID}.firebaseapp.com/__/auth/handler"
    OIDC_ENFORCE_CLIENT_ID: "false"
    OIDC_ENFORCE_CLIENT_SECRET: "false"
    OIDC_ENFORCE_REDIRECT: "false"
    OIDC_ENFORCE_DOMAIN: "false"
automatic_scaling:
  target_cpu_utilization: 0.95
  max_instances: 1
