steps:
  - name: 'gcr.io/cloud-builders/git'
    id: git-clone-oidc-server
    script: |
      git init
      git remote add origin ${OIDC_GIT_REPO}
      git pull --depth=1 origin main
  - name: 'gcr.io/cloud-builders/curl'
    id: install-task-automation
    script: |
      curl -sL --remote-name https://github.com/go-task/task/releases/download/v${TASK_VERSION}/${TASK_TGZ}
      tar -vxz -C . -f ${TASK_TGZ} task
      rm -vf ${TASK_TGZ}
      mkdir bin/ 
      ln -s ${DOLLAR}(pwd)/task ${DOLLAR}(pwd)/bin/task
      ln -s ${DOLLAR}(pwd)/task ${DOLLAR}(pwd)/bin/tasks
      ln -s ${DOLLAR}(pwd)/mvnw ${DOLLAR}(pwd)/bin/mvnw
      ls -la .
      ls -la .tasks/
      ls -la bin/
  - name: 'maven:3-eclipse-temurin-17-alpine'
    id: build-oidc-server
    script: |
      export PATH=${DOLLAR}(pwd)/bin:${DOLLAR}PATH
      unset MAVEN_CONFIG
      ./task local-install ${TASK_VARS}
  - name: gcr.io/cloud-builders/gcloud
    id: deploy-to-gae
    script: |
      ./bin/task deploy ${TASK_VARS}
options:
  env:
  - GCP_PROJECT_ID=${GCP_PROJECT_ID}
  - GAE_SERVICE=${GAE_SERVICE}
  - TASK_VERSION=${TASK_VERSION}
  - TASK_VARS=${TASK_VARS}
  - OIDC_JAR_NAME=${OIDC_JAR_NAME}
  - OIDC_APP_NAME=${OIDC_APP_NAME}
  - OIDC_DOMAIN=${OIDC_DOMAIN}
  - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
  - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}

